feat: adicionando o componente Footer a page Checkout
estartandodevs-course/organikos-frontend pull request #40
Opened 2022-10-24 23:24 UTC by lucasSlv

- Adicionando o componente Footer a page Checkout;

2022-10-24 23:26 UTC, ramonxm commented on src/pages/Checkout/styles.js
> +    position: absolute;
Qual foi o motivo pra ele ser absoluto?

2022-10-24 23:27 UTC, lucasSlv commented on src/pages/Checkout/styles.js
> +    position: absolute;
> Qual foi o motivo pra ele ser absoluto?

Não sei pq ela não estava indo para o fim da página, nas outras ele estava indo normalmente. Só consegui coloca-la com o absoluto

2022-10-24 23:32 UTC, ramonxm commented on src/pages/Checkout/styles.js
> +    position: absolute;
Ve se o container está pegando 100% do height.

2022-10-24 23:34 UTC, lucasSlv commented on src/pages/Checkout/styles.js
> +    position: absolute;
> Ve se o container está pegando 100% do height.

Pior que sim, até definir o height de 100% nele para testar

2022-10-24 23:47 UTC, ramonxm commented
@lucasSlv  dê pull na branch, n precisa do absolute.

<img width="169" alt="image" src="https://user-images.githubusercontent.com/38158476/197650838-29b2c492-e6dc-43f6-a6e8-4d207b52070d.png">
esses textos estão mt colados, verificar distancia no figma.

2022-10-24 23:47 UTC, ramonxm requested changes
@lucasSlv dê pull na branch, n precisa do absolute.

<img width="208" alt="image" src="https://user-images.githubusercontent.com/38158476/197650931-41dc07e5-06e5-4470-a264-2e0d55413af5.png">

esses textos estão mt colados, verificar distancia no figma.

2022-10-24 23:48 UTC, lucasSlv commented
> @lucasSlvdê puxar na ramificação, n precisa fazer absoluto.
> 
> <img alt="imagem" width="208" src="https://user-images.githubusercontent.com/38158476/197650931-41dc07e5-06e5-4470-a264-2e0d55413af5.png">
> 
> esses textos estão mt colados, controle distância no figma.

Ok

2022-10-25 00:33 UTC, ramonxm approved these changes

2022-10-25 00:34 UTC, merged