feat: button com estilização
estartandodevs-course/organikos-frontend pull request #7
Opened 2022-10-13 14:16 UTC by pablokaua

criando componente de botão

2022-10-13 14:18 UTC, lucasSlv approved these changes
LGTM!

2022-10-13 14:32 UTC, ramonxm requested changes

2022-10-13 14:32 UTC, ramonxm commented on src/components/Button/styles.js
> +  background-color: ${({ backgroundColor }) => backgroundColor};
Talvez seja bom colocar uma cor default para o botão.

Aconselho utilizar a primária que se repete em varios locais 
```suggestion
  background-color: ${({ backgroundColor }) => backgroundColor || 'cor primaria'};
```

2022-10-13 14:32 UTC, ramonxm commented on src/components/Button/styles.js
> +  width: 179px;
Não necessário visto que em baixo você está definindo width e height como 100%

2022-10-13 14:32 UTC, ramonxm commented on src/components/Button/styles.js
> +    background-color: ${({ backgroundColorHover }) => backgroundColorHover};
Adicionar uma cor default tbm.

2022-10-17 20:42 UTC, ramonxm commented on src/components/Button/styles.js
> +  width: 179px;
Ainda persiste

2022-10-17 20:43 UTC, ramonxm commented on src/components/Button/styles.js
> +  background-color: ${({ backgroundColor }) => backgroundColor};
Ainda persiste

2022-10-17 20:43 UTC, ramonxm commented on src/components/Button/styles.js
> +    background-color: ${({ backgroundColorHover }) => backgroundColorHover};
Ainda persite

2022-10-18 11:51 UTC, closed without merging